### ISSUE TITLE
Custom URL Origin

### ISSUE THREAD

**Issue by clickbrain** [n4ze3m/page-assist#147]
Hello,

This product is really pretty amazing. Thank you for creating it. 

I have Ollama running on MacStudio and am using ngrok to map it to a subdomain on a domain I am using. 

https://ollama.domain.com (not the actual domain)

It works well with a number of clients automatically, like Enchanted, BoltAI, etc from my macbook and from my phone. 

In page assist, when I have it in the URL box in settings I get the message in Chat window, that it cannot connect. 

I followed the instructions for the custom origin URL setup and it still does not work. Attaching screens so you can see what I mean. 

I've confirmed that Ollama is still working properly and everything is functioning as it should when accessing it remotely through other apps. 

Thank you for your help. 
![image](https://github.com/user-attachments/assets/c4bb307c-6f8e-4d7b-92cd-bd1eebbea4fd)

Brad

**Comment by n4ze3m** [comment]
Hey, sorry about this. This is a common issue with Page Assist since it runs directly client-side without any backend.

I tested this issue on a custom nrok server and noticed that if you put `https://ollama.domain.com/` as a custom header, it won't work. All you need to do is enable the custom header and set it to `http://127.0.0.1:11434`.

It should work fine. Please let me know if you still have any issues

![fRoHtImQHf](https://github.com/user-attachments/assets/dfa15be9-aad6-4407-9947-d7f7330c7b68)

**Comment by clickbrain** [comment]
That worked!  Thanks so much for getting on this.

**Comment by n4ze3m** [comment]
I'm closing this. Feel free to create a new one if you face any issues with Page Assist
